### ISSUE TITLE
at least patch backups if not fix it

### ISSUE THREAD

**Issue by dmarx** [pytti-tools/pytti-core#205]
https://discord.com/channels/869630568818696202/869675528494391307/988254689910984744

**Comment by Bardia323** [comment]
The issue was compatability of the subprocess with Windows. 
To resolve it, first:
`import platform`
which we use to find out the platform the code is being run in.

Then replace lines 145 to 150 with:
`if platform.platform().startswith("Win"):
   subprocess.run(["del", f"backup\\{file_namespace}\\{base_name}_{n-backups}.bak"] , shell=True, cwd=os.getcwd())
else: 
   subprocess.run(["rm", f"/backup/{file_namespace}/{base_name}_{n-backups}.bak"] , shell=True)`

**Comment by dmarx** [comment]
better yet, let's just use [`os.remove`](https://docs.python.org/3/library/os.html#os.remove) (which is cross-platform because it's native python) and drop the subprocess invocation entirely

**Comment by Bardia323** [comment]
Yep! Good idea! 👍

**Comment by dmarx** [comment]
Should I look out for a PR? It's pretty easy if you've never submitted one before.

**Comment by dmarx** [comment]
allrighty, merged into main! could you do me a favor and confirm that the fix worked? I don't have a windows system to test on.

**Comment by Bardia323** [comment]
I checked last night and didn't have any issues.  But I'll double check and
let you know tonight
