### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._six'

### ISSUE THREAD

**Issue by Sequential-circuits** [pytti-tools/pytti-core#227]
ModuleNotFoundError: No module named 'torch._six'

That module I understand is old as hell as it is for python 2, so is the system asking for it?

**Comment by dmarx** [comment]
you were on the right track but a little off. not that this is a submodule on torch: the issue here is a conflict between the pytorch version in colab and old code in taming-transformers (the code that runs the vqgan). i tweaked the taming fork pytti uses to resolve this issue and it seems to be working, but i think there are certain environment configurations in colab that may still cause other issues. take her for a spin though and let me know what happens
