### ISSUE TITLE
Drive Quota exceeded when doing video production

### ISSUE THREAD

**Issue by usergenic** [pytti-tools/pytti-core#95]
On Google Colab using Drive mounts, I have been running into quota exceeded errors which has the obnoxious result of the 0K files being sync'd onto Drive instead of the actual generated frames.  It's maddening.  This happen to anyone else?

I *think* maybe its not the frames being generated but might be the events.out.tfevents.* files in the logs folder.  Some of those files seem massive and I assume the appends to those files are frequent enough it might be an issue.  I believe Drive+Google Colab quota is quantity-of-transactions not quantity-of-bytes according to their docs, but I don't know what the hard numbers are or how to find out.

Please note this is when processing Video Source if that matters.  So it's possible that copying the mp4 video source to the Colab instance reduces seeks/reads on the input video too.  I'll try both.  Just filing issue in case anyone else has this problem.

**Comment by dmarx** [comment]
sorry to hear you're having issues with space limits :(

* that's a great call out about the tfevents stuff. I think I'm going to make tensorflow logging optional since it seems many people aren't using it anyway.
* here are some subfolders you should be able to safely delete that may be eating up space:
  * `logs` - this is where the tfevents stuff goes and you already noticed these files, mentioning here mainly for anyone else who stumbles across this
  * `backup` - this is associated with pytti's "resume" feature, which is non-functional for the moment anyway
  * `outputs` - hydra creates this folder and it can sometimes contain redundant content because... hydra is weird.
  * `multirun` - same thing as outputs. 

* > it's possible that copying the mp4 video source to the Colab instance reduces seeks/reads on the input video too  

  Interesting, so your thought here is that video source processing might be more efficient or less problematic if we add a procedure that copies the video file to the colab instance first? 

Let me know if that helps and what you end up finding wrt those folders, or any other observations you might have regarding unusual space consumption associated with PyTTI. 

Thanks again!

**Comment by usergenic** [comment]
FWIW I don't think its space limits-- I think its individual writes happening to append the logs.  That's the hunch based on the description of Colab/Drive quota at https://research.google.com/colaboratory/faq.html#drive-quota

**Comment by dmarx** [comment]
Ahhh gotcha, totally misunderstood. Thanks for that clarification.

**Comment by usergenic** [comment]
datapoint: after forcing the log folder to be "/tmp/logs" on my colab instance (i.e. not in drive mount) I have not had the quota issue. 🤘

**Comment by dmarx** [comment]
tensorboard is now optional, defaulting to False.
... just realized I need to test the colab. brb lol
